import type { Entity, Field } from '../types';
const text = (key: string, label: string, required = false): Field => ({ key, label, required });
const number = (key: string, label: string): Field => ({ key, label, type: 'number' });
const select = (key: string, label: string, source: string, required = true): Field => ({
  key,
  label,
  source,
  type: 'select',
  required,
});
const active: Field = { key: 'active', label: 'Ativo', type: 'checkbox' };
const description: Field = { key: 'description', label: 'Descrição', type: 'textarea' };
const notes: Field = { key: 'notes', label: 'Observações', type: 'textarea' };
const contact: Field[] = [
  text('responsible', 'Responsável'),
  text('phone', 'Telefone'),
  { key: 'email', label: 'E-mail', type: 'email' },
];
export const entities: Record<string, Entity> = {
  materials: {
    title: 'Materiais',
    singular: 'material',
    description: 'Acompanhe saldos, locais e limites do seu estoque.',
    writers: ['ADMIN', 'MANAGER', 'OPERATOR'],
    columns: [
      { key: 'code', label: 'Código' },
      { key: 'name', label: 'Material' },
      { key: 'category.name', label: 'Categoria' },
      { key: 'quantity', label: 'Saldo' },
      { key: 'unit', label: 'Unidade' },
      { key: 'stockStatus', label: 'Estoque' },
      { key: 'expiryDate', label: 'Validade' },
      { key: 'unitPrice', label: 'Valor unitário' },
      { key: 'active', label: 'Cadastro' },
    ],
    fields: [
      text('code', 'Código', true),
      text('barcode', 'Código de barras'),
      { key: 'expiryDate', label: 'Data de validade (opcional)', type: 'date' },
      text('name', 'Nome', true),
      select('categoryId', 'Categoria', 'categories'),
      text('unit', 'Unidade', true),
      number('minimum', 'Estoque mínimo'),
      number('maximum', 'Estoque máximo'),
      text('location', 'Localização'),
      text('shelf', 'Prateleira'),
      number('unitPrice', 'Valor unitário'),
      select('supplierId', 'Fornecedor', 'suppliers', false),
      active,
      description,
      notes,
    ],
  },
  categories: {
    title: 'Categorias',
    singular: 'categoria',
    description: 'Organize os materiais e bens por finalidade.',
    writers: ['ADMIN', 'MANAGER', 'OPERATOR'],
    columns: [
      { key: 'name', label: 'Nome' },
      { key: 'description', label: 'Descrição' },
      { key: 'active', label: 'Status' },
    ],
    fields: [text('name', 'Nome', true), active, description],
  },
  suppliers: {
    title: 'Fornecedores',
    singular: 'fornecedor',
    description: 'Cadastros e histórico de fornecimento.',
    writers: ['ADMIN'],
    columns: [
      { key: 'name', label: 'Razão social' },
      { key: 'cnpj', label: 'CNPJ' },
      { key: 'phone', label: 'Telefone' },
      { key: 'responsible', label: 'Responsável' },
      { key: 'active', label: 'Status' },
    ],
    fields: [
      text('name', 'Razão social', true),
      text('tradeName', 'Nome fantasia'),
      text('cnpj', 'CNPJ (14 dígitos)', true),
      ...contact,
      text('address', 'Endereço'),
      active,
      notes,
    ],
  },
  departments: {
    title: 'Setores',
    singular: 'setor',
    description: 'Consulte os setores e suas retiradas de materiais.',
    writers: ['ADMIN'],
    columns: [
      { key: 'name', label: 'Nome' },
      { key: 'acronym', label: 'Sigla' },
      { key: 'responsible', label: 'Responsável' },
      { key: 'phone', label: 'Telefone' },
      { key: 'active', label: 'Status' },
    ],
    fields: [text('name', 'Nome', true), text('acronym', 'Sigla', true), ...contact, active],
  },
  assets: {
    title: 'Patrimônio',
    singular: 'bem patrimonial',
    description: 'Identificação, localização e rastreabilidade dos bens.',
    writers: ['ADMIN', 'MANAGER'],
    columns: [
      { key: 'number', label: 'Tombamento' },
      { key: 'name', label: 'Bem' },
      { key: 'brand', label: 'Marca' },
      { key: 'location', label: 'Localização' },
      { key: 'responsible', label: 'Responsável' },
      { key: 'status', label: 'Situação' },
      { key: 'value', label: 'Valor' },
    ],
    fields: [
      text('number', 'Tombamento', true),
      text('name', 'Nome do bem', true),
      select('categoryId', 'Categoria', 'categories'),
      text('brand', 'Marca'),
      text('model', 'Modelo'),
      text('serialNumber', 'Número de série'),
      { key: 'acquisitionDate', label: 'Data de aquisição', type: 'date', required: true },
      number('value', 'Valor'),
      text('condition', 'Estado de conservação', true),
      text('location', 'Localização'),
      select('departmentId', 'Setor', 'departments'),
      text('responsible', 'Responsável', true),
      {
        key: 'status',
        label: 'Situação',
        type: 'select',
        required: true,
        options: Object.entries({
          IN_USE: 'Em uso',
          AVAILABLE: 'Disponível',
          MAINTENANCE: 'Em manutenção',
          TRANSFERRED: 'Transferido',
          DISPOSED: 'Baixado',
        }).map(([value, label]) => ({ value, label })),
      },
      description,
    ],
  },
  users: {
    title: 'Usuários',
    singular: 'usuário',
    description: 'Gerencie o acesso e as permissões da equipe.',
    writers: ['ADMIN'],
    columns: [
      { key: 'name', label: 'Nome' },
      { key: 'email', label: 'E-mail' },
      { key: 'registration', label: 'Matrícula' },
      { key: 'role', label: 'Perfil' },
      { key: 'active', label: 'Status' },
    ],
    fields: [
      text('name', 'Nome', true),
      { key: 'email', label: 'E-mail', type: 'email', required: true },
      text('registration', 'Matrícula', true),
      { key: 'password', label: 'Senha (mínimo 12 caracteres)', type: 'password' },
      {
        key: 'role',
        label: 'Perfil',
        type: 'select',
        required: true,
        options: [
          { value: 'ADMIN', label: 'Administrador' },
          { value: 'MANAGER', label: 'Gestor' },
          { value: 'OPERATOR', label: 'Operador' },
          { value: 'VIEWER', label: 'Consulta' },
        ],
      },
      active,
    ],
  },
};
